###
GET http://localhost:8000/be/category

###
GET http://localhost:8000/be/category/:id


###
POST http://localhost:8000/be/category
Content-Type: application/json

{
    "categoryName": "Eyepatch",
    "link": "/link"
}

###
PUT http://localhost:8000/be/category/:id
Content-Type: application/json

{
    "id": "ea21412c-1f26-40ff-8944-4c8e8452e2f1",
      "categoryName": "Menu",
      "link": "/link",
      "position": 1,
    
}
###
DELETE http://localhost:8000/be/category/3dd6c3fa-0bd5-4826-9344-8a0d61a68dec