###
POST http://localhost:8000/be/products
Content-Type: application/json

{
    "productName": "Men's sweater", 
    "categoryId": "", 
    "price": 500, 
    "discount": 20, 
    "quantity": 30, 
    "createdUser": "moog", 
    "description": "this product is ...", 
    "images": [], 
    "thumnail": ""
}

###
GET http://localhost:8000/be/products

###
GET http://localhost:8000/be/products/e7557d5f-4ec5-4c75-9712-5f3094fd8581

###
PUT http://localhost:8000/be/products/:id
Content-Type: application/json

{
    "id": "",
    "productName": "Men's sweater", 
    "categoryId": "", 
    "price": 500, 
    "discount": 20, 
    "quantity": 30, 
    "createdUser": "moog", 
    "description": "this product is ...", 
    "images": [], 
    "thumnail": ""
}
###
DELETE http://localhost:8000/be/menu/:id


